//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForSynaptic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectForSinapticEntities : DbContext
    {
        public ProjectForSinapticEntities()
            : base("name=ProjectForSinapticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authentitation> Authentitation { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<PriceList> PriceList { get; set; }
        public virtual DbSet<ProjectAccounting> ProjectAccounting { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<TypeProject> TypeProject { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
