//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForSynaptic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAccounting
    {
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDPrice { get; set; }
        public Nullable<int> IDType { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDProject { get; set; }
        public string Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual TypeProject TypeProject { get; set; }
        public virtual Users Users { get; set; }
    }
}
